CREATE TABLE USERS (U_ID NUMBER NOT NULL, NAME VARCHAR2(20), SURNAME VARCHAR2(20), USERNAME VARCHAR2(20), PASSWORD VARCHAR2(20), TIME_REG TIMESTAMP DEFAULT CURRENT_TIMESTAMP, CONSTRAINT USERS_PK PRIMARY KEY (U_ID));
CREATE SEQUENCE USERS_SEQ INCREMENT BY 1 START WITH 0 MINVALUE 0 NOCYCLE NOCACHE ORDER;

INSERT INTO USERS (U_ID, NAME, SURNAME, USERNAME, PASSWORD) VALUES(USERS_SEQ.NEXTVAL , 'PoN', 'Sudk', 'panichpon', '1234');
INSERT INTO USERS (U_ID, NAME, SURNAME, USERNAME, PASSWORD) VALUES(USERS_SEQ.NEXTVAL , 'PoN', 'Sudk', 'panichpon', '1234');
INSERT INTO USERS (U_ID, NAME, SURNAME, USERNAME, PASSWORD) VALUES(USERS_SEQ.NEXTVAL , 'PoN', 'Sudk', 'panichpon', '1234');
INSERT INTO USERS (U_ID, NAME, SURNAME, USERNAME, PASSWORD) VALUES(USERS_SEQ.NEXTVAL , 'PoN', 'Sudk', 'panichpon', '1234');
INSERT INTO USERS (U_ID, NAME, SURNAME, USERNAME, PASSWORD) VALUES(USERS_SEQ.NEXTVAL , 'PoN', 'Sudk', 'panichpon', '1234');

CREATE TABLE USERS_LOGS (UL_ID NUMBER NOT NULL, U_ID NUMBER, TIME_REG TIMESTAMP DEFAULT CURRENT_TIMESTAMP, CONSTRAINT USERS_LOGS_PK PRIMARY KEY (UL_ID), CONSTRAINT USERS_FK FOREIGN KEY (U_ID) REFERENCES USERS(U_ID));
CREATE SEQUENCE USERS_LOGS_SEQ INCREMENT BY 1 START WITH 0 MINVALUE 0 NOCYCLE NOCACHE ORDER;

INSERT INTO USERS_LOGS (UL_ID, U_ID) VALUES(USERS_LOGS_SEQ.NEXTVAL , 1);
INSERT INTO USERS_LOGS (UL_ID, U_ID) VALUES(USERS_LOGS_SEQ.NEXTVAL , 1);
INSERT INTO USERS_LOGS (UL_ID, U_ID) VALUES(USERS_LOGS_SEQ.NEXTVAL , 2);
INSERT INTO USERS_LOGS (UL_ID, U_ID) VALUES(USERS_LOGS_SEQ.NEXTVAL , 3);



SELECT * FROM USERS ORDER BY U_ID ASC;
SELECT * FROM USERS_LOGS ORDER BY UL_ID ASC;


DROP TABLE USERS;
DROP TABLE USERS_LOGS;
DROP SEQUENCE USERS_SEQ;
DROP SEQUENCE USERS_LOGS_SEQ;